// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: message_controller.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageController_NewMessage_FullMethodName   = "/api.MessageController/NewMessage"
	MessageController_ChatMessages_FullMethodName = "/api.MessageController/ChatMessages"
	MessageController_FriendsList_FullMethodName  = "/api.MessageController/FriendsList"
)

// MessageControllerClient is the client API for MessageController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageControllerClient interface {
	NewMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
	ChatMessages(ctx context.Context, in *Users, opts ...grpc.CallOption) (*ChatUsers, error)
	FriendsList(ctx context.Context, in *User, opts ...grpc.CallOption) (*List, error)
}

type messageControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageControllerClient(cc grpc.ClientConnInterface) MessageControllerClient {
	return &messageControllerClient{cc}
}

func (c *messageControllerClient) NewMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, MessageController_NewMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageControllerClient) ChatMessages(ctx context.Context, in *Users, opts ...grpc.CallOption) (*ChatUsers, error) {
	out := new(ChatUsers)
	err := c.cc.Invoke(ctx, MessageController_ChatMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageControllerClient) FriendsList(ctx context.Context, in *User, opts ...grpc.CallOption) (*List, error) {
	out := new(List)
	err := c.cc.Invoke(ctx, MessageController_FriendsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageControllerServer is the server API for MessageController service.
// All implementations must embed UnimplementedMessageControllerServer
// for forward compatibility
type MessageControllerServer interface {
	NewMessage(context.Context, *Message) (*Response, error)
	ChatMessages(context.Context, *Users) (*ChatUsers, error)
	FriendsList(context.Context, *User) (*List, error)
	mustEmbedUnimplementedMessageControllerServer()
}

// UnimplementedMessageControllerServer must be embedded to have forward compatible implementations.
type UnimplementedMessageControllerServer struct {
}

func (UnimplementedMessageControllerServer) NewMessage(context.Context, *Message) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMessage not implemented")
}
func (UnimplementedMessageControllerServer) ChatMessages(context.Context, *Users) (*ChatUsers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatMessages not implemented")
}
func (UnimplementedMessageControllerServer) FriendsList(context.Context, *User) (*List, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendsList not implemented")
}
func (UnimplementedMessageControllerServer) mustEmbedUnimplementedMessageControllerServer() {}

// UnsafeMessageControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageControllerServer will
// result in compilation errors.
type UnsafeMessageControllerServer interface {
	mustEmbedUnimplementedMessageControllerServer()
}

func RegisterMessageControllerServer(s grpc.ServiceRegistrar, srv MessageControllerServer) {
	s.RegisterService(&MessageController_ServiceDesc, srv)
}

func _MessageController_NewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageControllerServer).NewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageController_NewMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageControllerServer).NewMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageController_ChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Users)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageControllerServer).ChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageController_ChatMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageControllerServer).ChatMessages(ctx, req.(*Users))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageController_FriendsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageControllerServer).FriendsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageController_FriendsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageControllerServer).FriendsList(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageController_ServiceDesc is the grpc.ServiceDesc for MessageController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.MessageController",
	HandlerType: (*MessageControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewMessage",
			Handler:    _MessageController_NewMessage_Handler,
		},
		{
			MethodName: "ChatMessages",
			Handler:    _MessageController_ChatMessages_Handler,
		},
		{
			MethodName: "FriendsList",
			Handler:    _MessageController_FriendsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message_controller.proto",
}
